### PR TITLE
WIP feat: add whitelist channel check

### PR DESCRIPTION
**Pull request by kennyttotheleft**
# Overall

We need to control for channels that allow the bot to send messages for development because we have multiple environments (for production and PRs). 

For example, when you run a bot on both environments for PR and localhost, 
you see two messages for one trigger message.

スクリーンショット 2021-12-16 23 08 14

# What

- Add the whitelist check to send messages for the Discord bot.
- Add .env.sample file.
- Add config module.
- Add debug utility module.
- Add docs about the Discord bot.

# Note

Before merging this PR, please add these env vars to the production environment on Railway.
The value for the keys is the same (development-test channel ID)
`920167819360993330`

1. DEV_CHANNEL_WHITELIST
2. PROD_CHANNEL_WHITELIST

# Functional Check

1. ENV: local
    1. The messages should contain `[ENV: localhost]`.
    2. The messages should be sent only `development-test` channel.
1. ENV: development
    1.  The messages should contain `[ENV: {PR-CODE} BRANCH: {BRANCH_NAME}]`.
    1. The messages should be sent only `development-test` channel.
1. ENV: production
    1. The messages should not contain `[ENV: {PR-CODE} BRANCH: {BRANCH_NAME}]`.
    1. The messages should be sent only `development-test` channel.

### CODE REVIEW

**Comment by shunkakinoki** [comment]
@kennyttotheleft 
素敵なpr有難うございます！！

**Comment by kennyttotheleft** [comment]
# Functional check

## Check case

1. Development
    1. The bot message should be sent to the channel on the dev whitelist whenever a user sent a message `!ping`.
    1. Debug label should be printed in the bot message from the dev environment.
    1. `ENV` and `BRANCH` info should be printed in the debug label from the Railway dev environment (generated by the PR).
    1. `ENV` info should be printed in the debug label from the localhost.
1. Production
    1. The bot message should be sent to the channel on the prod whitelist whenever a user sent a message `!ping`.
    1. The Debug label should not be printed in the bot messages from the prod environment.

---

# 機能チェック

## チェック項目

1. Development 環境
     1. ユーザーがメッセージ `！ping`を送信するたびに、開発用ホワイトリストに登録されているチャネルにボットメッセージが送信されること。
     1. デバッグラベルは、開発環境からのボットメッセージに出力されること。
     1. `ENV`および` BRANCH`情報は、Railway dev 環境（PRによって自動生成される）からのデバッグラベルに出力されていること。
     1. `ENV`情報が、ローカルホストからのデバッグラベルに出力されていること。
1. Production 環境
     1. ユーザーがメッセージ `！ping`を送信するたびに、本番用ホワイトリストに登録されたチャネルにボットメッセージが送信されること。
     1. デバッグラベルは、本番環境からのボットメッセージには表示されていないこと。

**Comment by kennyttotheleft** [comment]
# Check Result

## Environmental info: Development
* Backend
  * Personal Railway project
  * localhost
* Discord
  * Personal server
* Discord channel setting
  Two text channels below were used.
  * `一般`: Not on the allowed list.
  * `test`: On the allowed list.

## [Result 🙆‍♂️ ] 1-1. The bot message should be sent to the channel on the dev allowed list.

The bot message was sent to the channel only on the dev allowed list 🙆‍♂️ 

| No. | Channel name | Allowed-listed | Expected | Actual | Result | Evidence |
|---|---|---|---|---|---|---|
| 1-1-1 | 一般 | No | Not sent | Not sent | 🙆‍♂️ | non-allowed-listed-channel-check |
| 1-1-2 | test | Yes | Sent | Sent | 🙆‍♂️  | allowed-listed-channel-check |

## [Result 🙆‍♂️ ] 1-2. Debug label should be printed in the bot message from the dev environment.

The debug label was printed in the message both from Railway and the localhost 🙆‍♂️ 

| No. | Environment | Expected | Actual | Result | Evidence |
|---|---|---|---|---|---|
| 1-2-1 | Railway (PR) | Printed | Printed | 🙆‍♂️ | dev-message-sending-check-railway |
| 1-2-2 | Localhost | Printed | Printed | 🙆‍♂️ | dev-message-sending-check-localhost |

## [Result 🙆‍♂️ ] 1-3. `ENV` and `BRANCH` info should be printed in the debug label from the Railway dev environment (generated by the PR).

`ENV` and `BRANCH` info was printed in the debug label from the Railway 🙆‍♂️ 

| No. | Environment | Label | Expected | Actual | Result | Evidence |
|---|---|---|---|---|---|---|
| 1-3-1 | Railway (PR) | ENV | Printed | Printed | 🙆‍♂️ | dev-message-sending-check-railway |
| 1-3-2 | Railway (PR) | BRANCH | Printed | Printed | 🙆‍♂️ | Same as above |

## [Result 🙆‍♂️ ] 1-4. ENV info should be printed in the debug label from the localhost.

`ENV` info was printed in the debug label from the localhost 🙆‍♂️ 

| No. | Environment | Label | Expected | Actual | Result | Evidence |
|---|---|---|---|---|---|---|
| 1-4-1 | Railway (PR) | ENV | Printed | Printed | 🙆‍♂️ | dev-message-sending-check-localhost |
| 1-4-2 | Railway (PR) | BRANCH | Not printed | Not printed | 🙆‍♂️ | Same as above |

**Comment by kennyttotheleft** [comment]
# Check Result: Production

## Environmental info: Production
* Backend
  * WAGUMI Railway project for the main branch
* Discord
  * WAGUMI server
* Discord channel setting
  The test channel was used for now.
  * `development-test`: On the whitelist.

## Result

### [🙆‍♂️] 2-1. The bot message should be sent to the channel on the prod whitelist.

The bot message was sent to the whitelisted channel (development-test channel) 🙆‍♂️ 

| No. | Environment | Expected | Actual | Result | Evidence |
|---|---|---|---|---|---|
| 2-1-1 | Railway (main) | Sent | Sent | 🙆‍♂️ | prod-whitelisted-channel-message-check-1 prod-whitelisted-channel-message-check-2 |

### [🙆‍♂️] 2-2. The debug label should not be printed in the bot message from the prod environment.

The debug label was not printed in the bot message from the prod environment 🙆‍♂️ 

| No. | Environment | Expected | Actual | Result | Evidence |
|---|---|---|---|---|---|
| 2-2-1 | Railway (main) | Not printed | Not printed | 🙆‍♂️ |prod-non-debug-label-check |

## Note
We will investigate duplicate `Pong.` message transmissions later 👀

**Pull request merged**
